const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const loader=q('.loader');addEventListener('load',()=>setTimeout(()=>loader.classList.add('done'),900));setTimeout(()=>loader.classList.add('done'),2400);
const header=q('header'),menu=q('.menu'),nav=q('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';if(!open){header.classList.remove('hide');nav.classList.remove('hide')}menu.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);document.body.classList.toggle('nav-open',!open)});qa('nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');if(e.target.classList.contains('num'))counter(q('[data-count]',e.target));observer.unobserve(e.target)}}),{threshold:.12});qa('.reveal').forEach(e=>observer.observe(e));
function counter(el){const end=+el.dataset.count,start=performance.now();const run=t=>{const p=Math.min(1,(t-start)/1200);el.textContent=Math.round(end*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(run)};requestAnimationFrame(run)}
const progress=q('.progress'),heroImg=q('.hero-media img'),heroOrbit=q('.hero-orbit'),heroTitle=q('.hero h1'),contactRing=q('.contact-ring'),caseImgs=qa('.case-image img'),cases=qa('.case');let target=0,current=0,last=0,px=0,py=0,running=false;
function frame(){current+=(target-current)*.09;const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${current/max})`;heroImg.style.transform=`translate3d(0,${current*.16}px,0) scale(1.08)`;heroOrbit.style.transform=`translate3d(${px}px,${py+current*.1}px,0) rotate(${current*.025}deg)`;heroTitle.style.transform=`translate3d(0,${current*.2}px,0)`;contactRing.style.transform=`rotate(${current*.018}deg) scale(${1+Math.sin(current*.002)*.04})`;caseImgs.forEach((img,i)=>{const r=img.parentElement.getBoundingClientRect(),d=(r.top+r.height/2-innerHeight/2);img.style.transform=`translate3d(0,${Math.max(-55,Math.min(55,-d*.08))}px,0) scale(1.08)`});cases.forEach((el,i)=>{const r=el.getBoundingClientRect(),d=r.top-innerHeight;el.style.transform=`translate3d(${Math.max(-22,Math.min(22,d*.018*(i%2?1:-1)))}px,0,0)`});if(Math.abs(target-current)>.1)requestAnimationFrame(frame);else running=false}
addEventListener('scroll',()=>{target=scrollY;const hiding=target>last&&target>180&&!document.body.classList.contains('nav-open');header.classList.toggle('scrolled',target>30);header.classList.toggle('hide',hiding);nav.classList.toggle('hide',hiding);last=target;if(!running){running=true;requestAnimationFrame(frame)}},{passive:true});addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5)*34;py=(e.clientY/innerHeight-.5)*34;if(!running){running=true;requestAnimationFrame(frame)}},{passive:true});frame();
const cursor=q('.cursor');addEventListener('pointermove',e=>cursor.animate({transform:`translate3d(${e.clientX}px,${e.clientY}px,0)`},{duration:380,fill:'forwards',easing:'cubic-bezier(.16,1,.3,1)'}));qa('.case a').forEach(e=>{e.addEventListener('mouseenter',()=>cursor.classList.add('view'));e.addEventListener('mouseleave',()=>cursor.classList.remove('view'))});
qa('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.16,y=(e.clientY-r.top-r.height/2)*.18;el.style.transform=`translate3d(${x}px,${y}px,0)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
qa('.case-image').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(1100px) rotateX(${-y*3.5}deg) rotateY(${x*3.5}deg) scale(.985)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
