const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,coarse=matchMedia('(pointer: coarse)').matches;
addEventListener('load',()=>setTimeout(()=>$('.intro')?.classList.add('done'),reduce?0:500));setTimeout(()=>$('.intro')?.classList.add('done'),2200);
const trigger=$('.menu-trigger'),nav=$('.nav-panel'),topbar=$('.topbar');function setMenu(open){trigger.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);nav.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('nav-open',open);if(open)setTimeout(()=>$('.nav-links a')?.focus(),300)}trigger.addEventListener('click',()=>setMenu(trigger.getAttribute('aria-expanded')!=='true'));$$('.nav-panel a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false);if(e.key==='Tab'&&nav.classList.contains('open')){const focusable=[trigger,...$$('a',nav)],first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');reveal.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>reveal.observe(e));
const sections=$$('[data-section]'),label=$('[data-section-label]');const sectionObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)label.textContent=e.target.dataset.section}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>sectionObs.observe(s));
let last=0,ticking=false;function onScroll(){if(ticking)return;ticking=true;requestAnimationFrame(()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;$('.scroll-progress').style.transform=`scaleX(${max?y/max:0})`;topbar.classList.toggle('hide',y>last&&y>180&&!document.body.classList.contains('nav-open'));last=y;ticking=false})}addEventListener('scroll',onScroll,{passive:true});onScroll();
const servicePreview=$('.service-preview'),serviceImg=$('.service-preview img');$$('.service').forEach(item=>{const button=$('button',item);function activate(){if(coarse){$$('.service').forEach(other=>{const active=other===item;other.classList.toggle('active',active);$('button',other).setAttribute('aria-expanded',String(active))})}else{serviceImg.src=item.dataset.preview;servicePreview.classList.add('show')}}button.addEventListener('click',activate);item.addEventListener('mouseenter',activate);item.addEventListener('mouseleave',()=>servicePreview.classList.remove('show'))});if(!coarse)addEventListener('pointermove',e=>{servicePreview.style.translate=`${Math.min(innerWidth-340,e.clientX+25)}px ${Math.min(innerHeight-260,e.clientY+25)}px`},{passive:true});
$$('.magnetic').forEach(el=>{if(coarse||reduce)return;el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate3d(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.16}px,0)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const steps=$$('.step');const stepObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){steps.forEach(s=>s.classList.remove('active'));e.target.classList.add('active')}}),{rootMargin:'-30% 0px -45%'});steps.forEach(s=>stepObs.observe(s));
const track=$('.case-track'),dots=$$('.case-dots button'),cases=$$('.case');if(track&&dots.length){let raf;track.addEventListener('scroll',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const i=Math.max(0,Math.min(cases.length-1,Math.round(track.scrollLeft/(cases[0].offsetWidth+14))));dots.forEach((d,n)=>d.classList.toggle('active',n===i))})},{passive:true});dots.forEach((d,i)=>d.addEventListener('click',()=>cases[i].scrollIntoView({behavior:reduce?'auto':'smooth',inline:'center',block:'nearest'})))}
function orbital(canvas,accent){if(!canvas)return;const ctx=canvas.getContext('2d'),dpr=Math.min(devicePixelRatio||1,2);let w,h,mx=.72,my=.48,t=0,run=true;function size(){w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}size();new ResizeObserver(size).observe(canvas);if(!coarse)canvas.parentElement.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mx+=(e.clientX/r.width-mx)*.35;my+=(e.clientY/r.height-my)*.35},{passive:true});const io=new IntersectionObserver(es=>run=es[0].isIntersecting);io.observe(canvas);function draw(){if(run){ctx.clearRect(0,0,w,h);const cx=w*mx,cy=h*my,r=Math.min(w,h)*(coarse?.26:.34);ctx.save();ctx.translate(cx,cy);ctx.rotate(reduce?0:t*.0015);for(let j=0;j<5;j++){ctx.beginPath();ctx.ellipse(0,0,r*(1+j*.18),r*(.28+j*.035),j*.43,0,Math.PI*2);ctx.strokeStyle=j===2?accent:`rgba(233,232,223,${.13-j*.012})`;ctx.lineWidth=j===2?1.4:.7;ctx.stroke()}for(let i=0;i<22;i++){const a=i/22*Math.PI*2+t*.00035*(i%2?1:-1),rr=r*(.4+(i%7)/9),x=Math.cos(a)*rr,y=Math.sin(a)*rr*.65;ctx.beginPath();ctx.arc(x,y,i%5===0?3.5:1.3,0,Math.PI*2);ctx.fillStyle=i%5===0?accent:'rgba(233,232,223,.5)';ctx.fill()}const g=ctx.createRadialGradient(0,0,0,0,0,r*.65);g.addColorStop(0,'rgba(223,255,0,.18)');g.addColorStop(1,'rgba(223,255,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r*.7,0,Math.PI*2);ctx.fill();ctx.font=`${Math.max(64,r*.8)}px Archivo Black`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='rgba(233,232,223,.92)';ctx.fillText('3π',0,0);ctx.restore();t+=16}requestAnimationFrame(draw)}draw()}
orbital($('#orbital-canvas'),'#dfff00');orbital($('#contact-canvas'),'#ff5b2e');
if(!reduce){const countObs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;$$('[data-count]',e.target).forEach(el=>{const end=+el.dataset.count,start=performance.now();function tick(now){const p=Math.min(1,(now-start)/1100);el.textContent=Math.round(end*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)});countObs.unobserve(e.target)}),{threshold:.3});countObs.observe($('.metrics'))}