const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,coarse=matchMedia('(pointer: coarse)').matches;
addEventListener('load',()=>setTimeout(()=>$('.intro')?.classList.add('done'),reduce?0:500));setTimeout(()=>$('.intro')?.classList.add('done'),2300);
const nav=$('.nav-shell'),trigger=$('.nav-trigger'),menu=$('.menu');
function setMenu(open){trigger.setAttribute('aria-expanded',String(open));menu.classList.toggle('open',open);menu.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open);if(open)setTimeout(()=>$('.menu-links a')?.focus(),450)}
trigger.addEventListener('click',()=>setMenu(trigger.getAttribute('aria-expanded')!=='true'));$$('.menu a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open')){setMenu(false);trigger.focus()}if(e.key==='Tab'&&menu.classList.contains('open')){const f=[trigger,...$$('a',menu)],first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const label=$('[data-scene-label]');new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)label.textContent=e.target.dataset.scene}),{rootMargin:'-42% 0px -52%'}).observe;
const sceneObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)label.textContent=e.target.dataset.scene}),{rootMargin:'-42% 0px -52%'});$$('[data-scene]').forEach(s=>sceneObs.observe(s));
const active=new Set;const activeObs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting?active.add(e.target):active.delete(e.target)),{rootMargin:'150px 0px'});$$('.hero,.thesis,.portfolio,.finale').forEach(s=>activeObs.observe(s));
let lastY=0;function motionFrame(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;$('.progress').style.transform=`scaleX(${max?y/max:0})`;nav.classList.toggle('compact',y>180&&innerWidth<601);nav.classList.toggle('hide',y>lastY&&y>200&&!document.body.classList.contains('menu-open'));if(!reduce){const hero=$('.hero');if(active.has(hero)){const p=Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/innerHeight));$('.hero-media img').style.transform=`scale(${1.06+p*.08}) translate3d(0,${p*3}%,0)`;$('.hero-sheen').style.transform=`translateX(${-70+p*160}%)`}const thesis=$('.thesis');if(active.has(thesis)){const r=thesis.getBoundingClientRect(),p=Math.max(0,Math.min(.999,-r.top/(r.height-innerHeight))),idx=Math.min(2,Math.floor(p*3));$$('.thesis-steps article').forEach((el,i)=>el.classList.toggle('active',i===idx));$('.thesis-core').style.transform=`rotate(${p*120}deg) scale(${.86+p*.18})`}const port=$('.portfolio');if(active.has(port)&&innerWidth>600){const r=port.getBoundingClientRect(),p=Math.max(0,Math.min(1,-r.top/(r.height-innerHeight))),track=$('.portfolio-track'),distance=Math.max(0,track.scrollWidth-innerWidth);track.style.transform=`translate3d(${-distance*p}px,0,0)`;$('[data-project-current]').textContent=String(Math.min(3,Math.floor(p*3)+1)).padStart(2,'0');$$('.project-media img').forEach((im,i)=>im.style.transform=`scale(1.08) translate3d(${(p-i/3)*-3}%,0,0)`)}}lastY=y;requestAnimationFrame(motionFrame)}requestAnimationFrame(motionFrame);
$$('.cap-stage article').forEach(card=>{const b=$('button',card);function activate(){if(coarse){$$('.cap-stage article').forEach(c=>{const on=c===card;c.classList.toggle('open',on);$('button',c).setAttribute('aria-expanded',String(on))})}else{$$('.cap-stage article').forEach(c=>c.classList.toggle('open',c===card));const stage=$('.cap-stage').getBoundingClientRect(),r=card.getBoundingClientRect();$('.cap-core').style.transform=`translate3d(${(r.left+r.width/2-(stage.left+stage.width/2))*.06}px,${(r.top+r.height/2-(stage.top+stage.height/2))*.06}px,0)`}}b.addEventListener('click',activate);card.addEventListener('mouseenter',activate)});
if(!coarse&&!reduce)$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate3d(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.16}px,0)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
function webglField(canvas){if(!canvas)return;const gl=canvas.getContext('webgl',{alpha:true,antialias:false,powerPreference:'high-performance'});if(!gl)return;const vs=`attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`,fs=`precision highp float;uniform vec2 r,m;uniform float t;float line(float v,float w){return 1.-smoothstep(w,w+1.5/r.y,abs(v));}void main(){vec2 uv=gl_FragCoord.xy/r;vec2 p=(gl_FragCoord.xy-.5*r)/r.y;vec2 c=vec2(.21,-.015)+(m-.5)*vec2(.08,.045);float a=0.;for(int i=0;i<6;i++){float fi=float(i);vec2 q=p-c;float an=fi*.49+t*.018*(mod(fi,2.)*2.-1.);q=mat2(cos(an),-sin(an),sin(an),cos(an))*q;q.y/=(.28+fi*.025);a+=line(length(q)-(.255+fi*.032),.0012);}float node=0.;for(int j=0;j<9;j++){float fj=float(j);float an=fj*.698+t*(.07+mod(fj,3.)*.018);vec2 n=c+vec2(cos(an),sin(an)*.38)*(.27+mod(fj,4.)*.028);node+=exp(-9000.*dot(p-n,p-n));}float cursor=exp(-65.*distance(uv,m));vec3 blue=vec3(.055,.24,.9);vec3 col=blue*(a*.52+node*.9+cursor*.11);float alpha=min(1.,a*.72+node+cursor*.08);gl_FragColor=vec4(col,alpha);}`;function sh(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s}const prog=gl.createProgram();gl.attachShader(prog,sh(gl.VERTEX_SHADER,vs));gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(prog,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(prog,'r'),um=gl.getUniformLocation(prog,'m'),ut=gl.getUniformLocation(prog,'t');let mx=.72,my=.48,tx=mx,ty=my,visible=true,start=performance.now();function size(){const d=Math.min(devicePixelRatio||1,coarse?1.2:1.6);canvas.width=Math.round(canvas.clientWidth*d);canvas.height=Math.round(canvas.clientHeight*d);gl.viewport(0,0,canvas.width,canvas.height)}size();new ResizeObserver(size).observe(canvas);if(!coarse)canvas.parentElement.addEventListener('pointermove',e=>{tx=e.clientX/innerWidth;ty=1-e.clientY/innerHeight},{passive:true});new IntersectionObserver(es=>visible=es[0].isIntersecting).observe(canvas);document.addEventListener('visibilitychange',()=>visible=!document.hidden&&canvas.getBoundingClientRect().bottom>0);function frame(now){if(visible){mx+=(tx-mx)*.04;my+=(ty-my)*.04;gl.uniform2f(ur,canvas.width,canvas.height);gl.uniform2f(um,mx,my);gl.uniform1f(ut,reduce?0:(now-start)/1000);gl.drawArrays(gl.TRIANGLES,0,6)}requestAnimationFrame(frame)}requestAnimationFrame(frame)}webglField($('#field'));
